services:
  carbon-relay-ng:
    container_name: carbon-relay-ng
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2003:2003"
      - "8081:8081"
    environment:
      - GRAFANA_NET_ADDR=carbon-clickhouse:2103
      - GRAFANA_NET_API_KEY=carbon-clickhouse-1:2103
    volumes:
      -  ${PWD}/templates/carbon-relay-ng.ini:/conf/carbon-relay-ng.ini
    links:
      - carbon-clickhouse:carbon-clickhouse-1
    depends_on:
      - carbon-clickhouse

  carbon-clickhouse:
    image: lomik/carbon-clickhouse:latest
    volumes:
      - ${PWD}/carbon-clickhouse/carbon-clickhouse.toml:/carbon-clickhouse.toml
      - ${PWD}/clickhouse/rollup.xml:/rollup.xml
    ports:
      - '2103:2103'
    command: carbon-clickhouse -config="/carbon-clickhouse.toml"
    depends_on:
      - clickhouse

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - ${PWD}/clickhouse/nopassword.xml:/etc/clickhouse-server/users.d/nopassword.xml
      - ${PWD}/clickhouse/rollup.xml:/etc/clickhouse-server/conf.d/rollup.xml
      - ${PWD}/clickhouse/graphite.xml:/etc/clickhouse-server/conf.d/graphite.xml
      - ${PWD}/clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  clickhouse_data:
    driver: local
