#!/usr/bin/env bash
#MISE description="Build the Docker image"

VERSION=$(cat .version)
export IMAGE_VERSION=${VERSION:-0}

docker build --tag "${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_VERSION}" \
             --tag "${IMAGE_REPO}/${IMAGE_NAME}:latest" \
             --platform 'linux/amd64' .
